name: Lint

on: [push]
defaults:
  run:
    shell: bash

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      - name: Download hadolint config file
        run: curl https://raw.githubusercontent.com/streamr-dev/.github/master/.hadolint.yaml?token=GHSAT0AAAAAABPMM7HB4W2OQAHLEXAJA2O2YQGDXEA -o ./.hadolint.yaml
      - name: check directory
        run: ls -al  
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ./Dockerfile
          config: ./.hadolint.yaml



